// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Tit46KdQ8BQBUNAS--NrL8ruiZjIxYw',
    appId: '1:1053625372190:web:27a072c8f17f4e33f6280f',
    messagingSenderId: '1053625372190',
    projectId: 'vigi-4e754',
    authDomain: 'vigi-4e754.firebaseapp.com',
    storageBucket: 'vigi-4e754.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjrpSQj2m2EAmi7kg-GQawS3v8G_jS3dc',
    appId: '1:1053625372190:android:1b95f3f113e2ae5cf6280f',
    messagingSenderId: '1053625372190',
    projectId: 'vigi-4e754',
    storageBucket: 'vigi-4e754.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmFceauI4e_yfJn5ZnoDohsgiY8Di2xBA',
    appId: '1:1053625372190:ios:cfe2aa09e227c19ef6280f',
    messagingSenderId: '1053625372190',
    projectId: 'vigi-4e754',
    storageBucket: 'vigi-4e754.appspot.com',
    androidClientId: '1053625372190-fvrl9qh5lvr0n28sbonura3djvesfo4k.apps.googleusercontent.com',
    iosClientId: '1053625372190-pj81pt35jhc79hfggv9ftifdjh540i78.apps.googleusercontent.com',
    iosBundleId: 'com.example.vigiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmFceauI4e_yfJn5ZnoDohsgiY8Di2xBA',
    appId: '1:1053625372190:ios:4b12bc737720bd83f6280f',
    messagingSenderId: '1053625372190',
    projectId: 'vigi-4e754',
    storageBucket: 'vigi-4e754.appspot.com',
    androidClientId: '1053625372190-fvrl9qh5lvr0n28sbonura3djvesfo4k.apps.googleusercontent.com',
    iosClientId: '1053625372190-ku06acaskju0gar8uctgnhpvr10ee2ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.vigiApp.RunnerTests',
  );
}
